/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JFileChooser;

/**
 *
 * @author Welinton
 */
public class ConfigVIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfigVIEW
     */
    public ConfigVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLblBackgroud = new javax.swing.JLabel();
        jTxtFldBackground = new javax.swing.JTextField();
        jBtnAbrirImg = new javax.swing.JButton();
        jLblUf = new javax.swing.JLabel();
        jTxtFldUf = new javax.swing.JTextField();
        jLblCaminhoDB = new javax.swing.JLabel();
        jTxtFldCaminhoDB = new javax.swing.JTextField();
        jBtnAbrirDB = new javax.swing.JButton();
        jPnlRodape = new javax.swing.JPanel();
        jBtnGravar = new javax.swing.JButton();
        jBtnFechar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setTitle("Configurações do sistema");

        jLblBackgroud.setText("Plano de fundo");

        jBtnAbrirImg.setText("Abrir");

        jLblUf.setText("UF Padrão");

        jLblCaminhoDB.setText("Caminho banco de dados");

        jBtnAbrirDB.setText("Abrir");
        jBtnAbrirDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAbrirDBActionPerformed(evt);
            }
        });

        jBtnGravar.setText("Gravar");

        jBtnFechar.setText("Fechar");

        javax.swing.GroupLayout jPnlRodapeLayout = new javax.swing.GroupLayout(jPnlRodape);
        jPnlRodape.setLayout(jPnlRodapeLayout);
        jPnlRodapeLayout.setHorizontalGroup(
            jPnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlRodapeLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jBtnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnFechar)
                .addGap(18, 18, 18))
        );
        jPnlRodapeLayout.setVerticalGroup(
            jPnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGravar)
                    .addComponent(jBtnFechar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblBackgroud)
                            .addComponent(jLblUf)
                            .addComponent(jTxtFldUf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblCaminhoDB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtFldCaminhoDB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(jTxtFldBackground, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnAbrirImg)
                                    .addComponent(jBtnAbrirDB))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblBackgroud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAbrirImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblUf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFldUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCaminhoDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldCaminhoDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAbrirDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAbrirDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAbrirDBActionPerformed
        JFileChooser fc = new JFileChooser();
        int opcao;
        opcao = fc.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            jTxtFldCaminhoDB.setText(fc.getSelectedFile().getAbsolutePath());
            //System.out.println("Arquivo selecionado: "
            //   + fc.getSelectedFile().getName());
        }
    }//GEN-LAST:event_jBtnAbrirDBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbrirDB;
    private javax.swing.JButton jBtnAbrirImg;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLblBackgroud;
    private javax.swing.JLabel jLblCaminhoDB;
    private javax.swing.JLabel jLblUf;
    private javax.swing.JPanel jPnlRodape;
    private javax.swing.JTextField jTxtFldBackground;
    private javax.swing.JTextField jTxtFldCaminhoDB;
    private javax.swing.JTextField jTxtFldUf;
    // End of variables declaration//GEN-END:variables
}
